### ISSUE TITLE
Do i need to set bids or can i just run on global options

### ISSUE THREAD

**Issue by microton79** [derfabsSL/Splinterbuyer#10]
Hi!

If i want the bot too look at all undervalued cards can i just use the global options?
What does the number after the colon mean when starting the bot for Example:  
all cards, min 500CP/DEC: 0.0015400000000000001 <- This Number

**Comment by derfabsSL** [comment]
For global options, how it works is it looks at the market price for the cheapest card in the bid.
The number you see is this lowest price.
So at the moment you need to set an individual bid for each card you want the bot to buy.

I might add an option soon to calculate prices for all cards separately, keep an eye open for updates in the coming week :).
