### ISSUE TITLE
Dont buy

### ISSUE THREAD

**Issue by Drag2killer** [derfabsSL/Splinterbuyer#11]
Hello, my Bot run now over 24h with 5% under market price the but run and every 10-20 minits i get this massage 

error occured while checking cards: TypeError("calc_cp_per_usd() missing 1 required positional argument: 'price_usd'")
C-334 $0.023
error occured while checking cards: TypeError("calc_cp_per_usd() missing 1 required positional argument: 'price_usd'")
G-357 $1.8
C-349 $0.021
unable to parse: C-5NVU2SJIYO, looking up cardid...
https://steemmonsters.com/cards/find?ids=C1-45-5N7LJBRA0G
error occured while checking cards: NameError("name 'cardid' is not defined")

the bot buy no card in 24h
can u help me pls :(

**Comment by Drag2killer** [comment]
Thx :) and a question can the bot bid on all cards with    "cards": [""], ?

**Comment by derfabsSL** [comment]
Should work now.

You can bid on all cards like this:
        {
            "comment": "all cards,",
            "cards": [],
            "editions": ["alpha", "beta", "promo", "reward", "untamed", "dice", "chaos"],
            "rarities": ["common", "rare", "epic", "legendary"],
            "elements": ["fire", "water", "earth", "death", "life", "dragon", "neutral"],
            "types": ["summoner", "monster"],
            "min_bcx": 0,
            "min_cp_per_usd": 0,
            "max_price": 100,
            "max_quantity": 1,
            "gold_only": false,
            "exclude_cl": false,
            "sell_for_pct_more": 0
        }

**Comment by Drag2killer** [comment]
hey i download the new bot, but i get this massage again

error occured while checking cards: NameError("name 'cardid' is not defined")
C-331 $0.02
C-332 $6.7
C-343 $0.025
error occured while checking cards: NameError("name 'cardid' is not defined")
error occured while checking cards: NameError("name 'cardid' is not defined")
C-343 $0.022

**Comment by Drag2killer** [comment]
my bot work now :) thx but 100% RC for buy failed: The specified market items are no longer available for purchase.

can i start the bot  only with the Bid system?

**Comment by derfabsSL** [comment]
At the moment yes.
Do you have a suggestion for another way?
