### ISSUE TITLE
max_price

### ISSUE THREAD

**Issue by sovkil** [derfabsSL/Splinterbuyer#14]
hello, I can't figure out how to write the card price limit correctly. for example, I want to buy cards no more than $0.1. There is an example in the manual:
"max_price": [69.42]

I tried to specify:
"max_price": [0.1]

the bot bought cards much more expensive.

I tried to specify as in the example in the file (without brackets):
"max_price": 0.1

and that didn't work either.

tell me please how to do it right?

**Comment by derfabsSL** [comment]
Did you set auto_set_buy_price to true?

**Comment by sovkil** [comment]
Hi!

now the code is: 

    "global_params": {
        "currency": "DEC",
        "auto_set_buy_price": true,

****
"max_price": 0.1,

***

bot just bought a card for $0.15

**Comment by derfabsSL** [comment]
auto_set_buy_price needs to be false for the individual max_price to work

**Comment by sovkil** [comment]
then I don't understand how to buy cards cheaper by x% of the market price, but at the same time not to buy cards more expensive than "y"$. For example, I want to buy all the chaos below the market by 10% but at a cost no more than $ 0.1 - how to do this?

**Comment by derfabsSL** [comment]
This is not implemented yet, but expect an update soon

**Comment by sovkil** [comment]
that would be cool!  
could it be that the bot is trying to buy the same card several times? here's what I saw in the terminal: (purchases did not take place)

Line 6505: C-409 $0.043 - buying...
Line 6572: C-409 $0.043 - buying...
Line 6592: C-409 $0.043 - buying...
Line 6644: C-409 $0.043 - buying...
Line 6743: C-409 $0.043 - buying...
Line 6758: C-409 $0.043 - buying...
Line 6770: C-409 $0.043 - buying...
Line 6798: C-409 $0.043 - buying...
Line 7201: C-409 $0.043 - buying...
Line 7288: C-409 $0.043 - buying...
Line 7336: C-409 $0.043 - buying...
Line 7454: C-409 $0.043 - buying...

**Comment by derfabsSL** [comment]
Someone listed several different copies the same card at once, the bot is trying to buy all 12 cards

**Comment by derfabsSL** [comment]
This is now implemented, check out the newest release!
