### ISSUE TITLE
Check if there is enough balance before trying to buy a card.

### ISSUE THREAD

**Issue by ZeroCool940711** [derfabsSL/Splinterbuyer#3]
Hi there, I think the bot should make sure we have enough DEC or Credit before trying to buy a card, that way the transaction doesn't fail and it doesn't waste RC, even if checking the balance every now and then uses RC (which I'm not sure if it does) it will be better than having multiple transaction fail which would waste a lot more RC, in my case I've seen the bot fail continuously more than 10 times both for the same card or multiple cards.

**Comment by derfabsSL** [comment]
This is not currently planned, as it would slow down the bot.
You can use the field "max_quantity" to buy only the amount of cards you have the money for.
