### ISSUE TITLE
Make the bot able to buy cards based on Collection Power.

### ISSUE THREAD

**Issue by ZeroCool940711** [derfabsSL/Splinterbuyer#5]
Hi there, would be nice to have an option to buy cards with a minimum CP (Collection Power), this would help us build a better deck for reaching certain league, also would be nice to buy cards based on their elements, for example, buying Neutral or Fire cards.

**Comment by derfabsSL** [comment]
Filtering for elements is now possible, buying by CP might come in a future update, until then you can use [this chart](https://static.wikia.nocookie.net/splinterlands/images/9/94/SL_Power_Chart_V3.png/revision/latest?cb=20211112223250)
