### ISSUE TITLE
Newest code jsondecodererror

### ISSUE THREAD

**Issue by klbcolt** [derfabsSL/Splinterbuyer#9]
Exception has occurred: JSONDecodeError
Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

  File "[C:\Users\kevin\Desktop\Splinterbuyer-3.0]() - Copy\Splinterbuyer.py", line 267, in check_for_sold
    history = json.loads(response.text)
  File "[C:\Users\kevin\Desktop\Splinterbuyer-3.0]() - Copy\Splinterbuyer.py", line 316, in <module>
    check_for_sold()

b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n'

**Comment by klbcolt** [comment]
b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n'

**Comment by derfabsSL** [comment]
should work fine now, I updated the files in the release

**Comment by klbcolt** [comment]
Thank you for the change of .io to .com, but it didn't fix the issue.   I'm still getting the same exception.   I was able to get it to work by changing api to api2
